name: Check
on:
  push:
  pull_request:

jobs:
  validate-jsonld:
    runs-on: ubuntu-latest
    env:
      R_LIBS_USER: tempdir/Library
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: R -e 'install.packages("devtools")'
      - name: Setup devtools
        run: cd tests/ && R -e "devtools::install()"
      - name: Run tests
        run: cd tests/ && R -f test.R
  validate-crosswalks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run aggregate.py
        run: python3 scripts/aggregate.py
